name: Update NPM Package on Push
on:
  push:
    branches:
      - master

jobs:
  update-npm-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Git
        run: |
          git config user.email "osmanovramil823@gmail.com"
          git config user.name "Ramil Osmanov"

      - name: Install npm dependencies
        run: npm install

      - name: Update package code
        run: |
          npm update @rossmanov/micro-1
          npm version patch
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
