name: Update NPM Package on Push
on:
  push:
    branches:
      - master

jobs:
  update-npm-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Git
        run: |
          git config user.email "osmanovramil823@gmail.com"
          git config user.name "Ramil Osmanov"

      - name: Install npm dependencies
        run: npm install

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Login to npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Check Git status
        run: git status

      - name: Update package version
        run: npm version patch --no-git-tag-version

      - name: Publish updated package
        run: npm publish --access public
